### ISSUE TITLE
[Bug] Stress write trace data got OOM at the data node

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking#13522]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

When I stress-test with write trace data in the BanyanDB cluster, I get an OOM at the data node. 

Here is the screen of the liaison and data nodes. 
<img width="1674" height="644" alt="Image" src="https://github.com/user-attachments/assets/3e7cf217-da2b-49db-885a-e9a46dc94163" />
<img width="1662" height="702" alt="Image" src="https://github.com/user-attachments/assets/16442b96-a45f-434d-bd22-7ca143d5718d" />

I see there are some warning logs at the data node:
```
{"level":"info","module":"SERVER-QUEUE-SUB","session_id":"sync-1758874821920614384","topic":"v1:trace-part-sync","total_parts":327,"time":"2025-09-26T08:20:21Z","message":"started chunked sync session"}
{"level":"info","module":"SERVER-QUEUE-SUB","session_id":"sync-1758874821920614384","success":true,"bytes_received":275331039,"duration_ms":3770,"time":"2025-09-26T08:20:25Z","message":"completed chunked sync session"}
{"level":"warn","module":"ZIPKINTRACE.SEGID-20251004.SHARD0","beforeTotalCount":181194,"afterTotalCount":181194,"beforePartCount":180,"elapsed":132073.705797,"time":"2025-09-26T08:20:26Z","message":"background merger takes too long"}
{"level":"info","module":"SERVER-QUEUE-SUB","session_id":"sync-1758874925024020203","success":true,"bytes_received":262093978,"duration_ms":3835,"time":"2025-09-26T08:22:08Z","message":"completed chunked sync session"}
{"level":"warn","module":"MEMORY-PROTECTOR","used":"3.6 GB","limit":"3.2 GB","time":"2025-09-26T08:22:09Z","message":"memory usage exceeds limit"}
{"level":"warn","module":"MEMORY-PROTECTOR","used":"3.7 GB","limit":"3.2 GB","time":"2025-09-26T08:22:14Z","message":"memory usage exceeds limit"}
```

Here is the related heap profiling dump: 

[heap-data-batch.zip](https://github.com/user-attachments/files/22557304/heap-data-batch.zip)

### What you expected to happen

No OOM Kill at the data node.

### How to reproduce

1. Starting a 2 liaison and 2 data node cluster.
2. Keep writing trace data. 

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hanahmily** [comment]
@mrproliu Would you pls dump the heap when the heap size is too large? All the heaps you dumped are less than 30MB.

**Comment by mrproliu** [comment]
I have re-uploaded the files and am conducting three batch continue profiling sessions.

**Comment by hanahmily** [comment]
The root cause is that **the liaison continues to send data to the data nodes without pause**, even when these nodes are experiencing memory pressure. This memory pressure arises from unflushed memory parts that the liaison has written.

For a quick resolution, I will increase the number of working threads to speed up the flushing and merging process. According to the diagram, the CPU of the data node has the capacity to handle additional flushing activities.

For long-term improvement, we need to implement a backpressure process to throttle the data flow from the liaison.

@mrproliu you could work on reducing the traffic to prevent the data node from OOM. BTW, I didn't find the index data. Do you set the index rules for trace?

**Comment by mrproliu** [comment]
> @mrproliu you could work on reducing the traffic to prevent the data node from OOM. 

Yes, I could send the trace data with a smaller trace count per streaming, and add a thread sleep for each streaming send. 

> BTW, I didn't find the index data. Do you set the index rules for trace?

I added it today, but I got the same result.

**Comment by mrproliu** [comment]
I have reduced the trace count (50) per streaming, and each streaming needs to sleep (wait) for 300 milliseconds; however, the situation is not better.

**Comment by mrproliu** [comment]
BTW, the memory usage decreases when I have already closed the stress test client almost 2 minutes. 

<img width="1663" height="660" alt="Image" src="https://github.com/user-attachments/assets/c9607d82-32d8-43c6-9acb-c1549bf0fc6a" />

<img width="1657" height="594" alt="Image" src="https://github.com/user-attachments/assets/66fe9721-404b-43e3-9381-4a6c9a8a80d2" />

**Comment by hanahmily** [comment]
> BTW, the memory usage decreases when I have already closed the stress test client almost 2 minutes.
> 
> <img alt="Image" width="1663" height="660" src="https://private-user-images.githubusercontent.com/3417650/494875194-c9607d82-32d8-43c6-9acb-c1549bf0fc6a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkxMDIyNDIsIm5iZiI6MTc1OTEwMTk0MiwicGF0aCI6Ii8zNDE3NjUwLzQ5NDg3NTE5NC1jOTYwN2Q4Mi0zMmQ4LTQzYzYtOWFjYi1jMTU0OWJmMGZjNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjhUMjMyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVmZmRmNzRlMGI0NDMxMDM4YTIxYzBhZDk3MDUyMDRmZDI3NDcwM2ZmZTBlNTViOGIxYzc0YTg1ZDA4MjExMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CNOFq17T5Zue0C5Gn-pHzqhFqJxI-O-dTcUyQzbLIaI"> <img alt="Image" width="1657" height="594" src="https://private-user-images.githubusercontent.com/3417650/494875243-66fe9721-404b-43e3-9381-4a6c9a8a80d2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkxMDIyNDIsIm5iZiI6MTc1OTEwMTk0MiwicGF0aCI6Ii8zNDE3NjUwLzQ5NDg3NTI0My02NmZlOTcyMS00MDRiLTQzZTMtOTM4MS00YTZjOWE4YTgwZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjhUMjMyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg1NzY4YjBmMWFiYjU4NjNmZDc1NWEzOTNiZDlkZTRmYjY4OWM0NjliYmJlNWQ1NWRiZDI5NjAyYjIwODRiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dt1Dzn78CXjxJeZhSI_yWZHOpGgpjGdSIZfMJUdqezs">

Would you help me understand the issue by answering:

1. The pods are killed due to OOM during the test?
2. If there are some errors in the console?
3. Would you dump the heap to help me analyze the reason as before?

**Comment by mrproliu** [comment]
> The pods are killed due to OOM during the test?

Yes, I have watched the pods, here is the realted command result.

```
$ kubectl get pods -A --watch
...
banyandb          banyandb-data-hot-0                                          0/1     OOMKilled   1 (4m15s ago)   10h
banyandb          banyandb-data-hot-1                                          0/1     OOMKilled   1 (4m16s ago)   10h
banyandb          banyandb-data-hot-0                                          0/1     CrashLoopBackOff   1 (15s ago)     10h
banyandb          banyandb-data-hot-0                                          0/1     Running            2 (15s ago)     10h
banyandb          banyandb-data-hot-1                                          0/1     CrashLoopBackOff   1 (15s ago)     10h
banyandb          banyandb-data-hot-1                                          0/1     Running            2 (15s ago)     10h
banyandb          banyandb-data-hot-1                                          0/1     Running            2 (27s ago)     10h
banyandb          banyandb-data-hot-0                                          0/1     Running            2 (29s ago)     10h
banyandb          banyandb-data-hot-1                                          1/1     Running            2 (58s ago)     10h
banyandb          banyandb-data-hot-0                                          1/1     Running            2 (60s ago)     10h
```

> If there are some errors in the console?
> Would you dump the heap to help me analyze the reason as before?

There are no error logs in the console.  I have dumped the heap and logs into this file: 

[banyandb-data.zip](https://github.com/user-attachments/files/22586692/banyandb-data.zip)

**Comment by hanahmily** [comment]
This issue is from the secondary index merging. Could you remove the index rule to recheck it with lower traffic?

> [banyandb-data.zip](https://github.com/user-attachments/files/22586692/banyandb-data.zip)

**Comment by mrproliu** [comment]
After I removed the index rule and kept using small traffic, the problem was resolved. 

<img width="1869" height="640" alt="Image" src="https://github.com/user-attachments/assets/d72413fb-9ee9-4d7d-afd6-8e7f56f548e6" />

<img width="1875" height="554" alt="Image" src="https://github.com/user-attachments/assets/7103961a-32d6-4d7b-91bd-c0f1ca334eee" />

But when I keep removing the index rule and sending large traffic to the banyanDB, the problem seems to exist. But you have mentioned the performance issue, so I think I can close this issue for now. Here are the large traffic-related screenshots. 

<img width="1898" height="607" alt="Image" src="https://github.com/user-attachments/assets/cc386147-1d61-4279-a3e1-007c84561533" />

<img width="1904" height="553" alt="Image" src="https://github.com/user-attachments/assets/8d270cf4-be94-48bb-9457-4b3e758fd89c" />

<img width="1635" height="602" alt="Image" src="https://github.com/user-attachments/assets/257da994-ac8b-4479-bf0b-81fcc3b50db3" />

**Comment by wu-sheng** [comment]
I think index merging is still an issue, isn't it?
By removing index rules, we just know it is the reason. But we didn't fix anything yet.
