### ISSUE TITLE
[Agent Plugin] Lambda instrumentation

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking#4256]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

This is a big story to instrument the lambda expressions in JDK8+, lambda can be essentially a `Runnable`, `Callable`, `Function`, `Consumer` and many many others `FunctionalInterface`-annotated interfaces, but for now we're planning to support only a few of them:

- [ ] Threading-related, such as `Runnable`, `Callable`;
- [ ] Streaming-related, `java.util.concurrent.ForkJoinPool` essentially

**Comment by JohnNiang** [comment]
I'm trying to refactor with new feature in JDK8+. : P

**Comment by wu-sheng** [comment]
Moving this to help wanted as no progress and this is not critical.

**Comment by xbkaishui** [comment]
Hi I want have a try, since I am not familiar with this，can anyone give me some clues ?  thanks

**Comment by wu-sheng** [comment]
@xbkaishui Have you familiar with Lambda? This is a JDK level feature. 

@kezhenxu94 Could you provide more details?

**Comment by xbkaishui** [comment]
I found the entry point (LambdaMetafactory class) base on this article [lambda-inspection](https://ruediste.github.io/bytecode/2017/02/25/lambda-inspection.html)
I will try to test in my local env and submit a PR

**Comment by wu-sheng** [comment]
Note, Lambda is also widely used in the rt.jar and many framework. I think the key point of this, we should only instrument user's lambda.

**Comment by kezhenxu94** [comment]
Sorry I'm late, here is another answer from the author of bytebuddy, just FYI https://stackoverflow.com/a/33912156/5200161

**Comment by xbkaishui** [comment]
> Sorry I'm late, here is another answer from the author of bytebuddy, just FYI https://stackoverflow.com/a/33912156/5200161

Thanks for your help

**Comment by xbkaishui** [comment]
> Note, Lambda is also widely used in the rt.jar and many framework. I think the key point of this, we should only instrument user's lambda.

Yes, I have no good idea about this, I think we should let user choose which package should be instrumented, is that ok ?

**Comment by kezhenxu94** [comment]
> > Note, Lambda is also widely used in the rt.jar and many framework. I think the key point of this, we should only instrument user's lambda.
> 
> 
> 
> Yes, I have no good idea about this, I think we should let user choose which package should be instrumented, is that ok ?  

That's a feasible option in the current agent design

**Comment by wu-sheng** [comment]
> Note that this does only work with OpenJDK 8u40, in previous versions, there is a bug related to invokedynamic call sites that prevents this from working.

This makes me concern about feasibility in the real world. And you need `.with(LambdaInstrumentationStrategy.ENABLED)`, which can't be done through the plugin system. Do you have any idea/design about this?

**Comment by xbkaishui** [comment]
The article @kezhenxu94 provider is too old, I am not sure if the latest version has any change,  I will test first to see how happened, anyway for this feature I think we should provider two property is agent config:
1. Enable lambda instrumentation switch (Yes/No)
2.Choose which package should be instrumented (List<String>)

**Comment by wu-sheng** [comment]
Please don't instrument all lambda in any case. We at least require the package name.

**Comment by wu-sheng** [comment]
I doubt JVM will change the class loader mechanism, in this case, lambda load mechanism. JVM load is usually defined in the Java specification.

**Comment by xbkaishui** [comment]
Progress update, The current implementation of lambda in jdk8 is to generate anonymous internal classes from the code inside the lambda. The classloader is appClassloader, and the invokeDymanic command is used for dynamic binding calls. The current implementation idea is to inject  the obtain the span logic into generated anonymous internal class,
 It's not easy to do this

**Comment by wu-sheng** [comment]
Could you provide more details? I don't think internal class is an issue. The previous issue is anonymous class loader.

**Comment by xbkaishui** [comment]
Yes, will show the test case later, I am a litter busy this days

**Comment by xbkaishui** [comment]
After some deep investigate, I found it's hard to do this with bytebuddy, 
errors is open jdk9 
```
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.bind.Binder$$Lambda$ByteBuddy$102
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:129) ~[chapter3-3-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 41 mor
```
according to the author, it is a bug related to [jdk](https://bugs.openjdk.java.net/browse/JDK-8145964) 
I also test in open jdk11, there are some errors too.
```
Caused by: java.lang.IllegalAccessException: class java.lang.invoke.LambdaMetafactory (in module java.base) cannot access class jdk.xml.internal.SecuritySupport$$Lambda$ByteBuddy$36/0x0000000800342840 (in module java.xml) because module java.xml does not export jdk.xml.internal to module java.base
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)
	... 36 more
```

**Comment by wu-sheng** [comment]
The JDK-8145964 has been tagged as resolved in b135.

**Comment by xbkaishui** [comment]
I have tested in openjdk version "9" still fails 
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

```
INFO 2020-09-15 22:12:27:128 main SnifferConfigInitializer : Config file found in /tmp/apache-skywalking-apm-bin/agent/config/agent.config.
ERROR StatusLogger Could not reconfigure JMX
 java.lang.NoClassDefFoundError: Could not initialize class java.lang.management.ManagementFactory$PlatformMBeanFinder
	at java.management/java.lang.management.ManagementFactory.platformComponents(ManagementFactory.java:907)
	at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:478)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:139)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
	at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)
	at com.didispace.chapter33.Chapter33Application.main(Chapter33Application.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
[22:12:31.316] ERROR org.apache.logging.log4j.util.StackLocator 71 calcLocation - Application run failed java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/bind/Binder$$Lambda$ByteBuddy$101
	at jdk.internal.misc.Unsafe.defineAnonymousClass0(Native Method) ~[?:?]
	at jdk.internal.misc.Unsafe.defineAnonymousClass(Unsafe.java:1204) ~[?:?]
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java) ~[?:?]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:332) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:250) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:240) ~[?:?]
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:409) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:375) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:319) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:308) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:238) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:199) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.getProfiles(ConfigFileApplicationListener.java:652) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.initializeProfiles(ConfigFileApplicationListener.java:368) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$load$0(ConfigFileApplicationListener.java:342) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader$$Lambda$ByteBuddy$92/1020897892.accept(Unknown Source) ~[?:?]
	at org.springframework.boot.context.config.FilteredPropertySource.apply(FilteredPropertySource.java:54) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:336) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:226) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:210) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:200) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:188) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
	at com.didispace.chapter33.Chapter33Application.main(Chapter33Application.java:12) [classes!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [chapter3-3-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [chapter3-3-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [chapter3-3-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [chapter3-3-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.bind.Binder$$Lambda$ByteBuddy$101
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:129) ~[chapter3-3-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 41 more

```

**Comment by wu-sheng** [comment]
If you really want to do this, I recommend you submit a question on the byte buddy repo, with a simple demo case, not SkyWalking's. It is too complex. If that works, we could discuss more about how to move it back into SkyWalking.

**Comment by xbkaishui** [comment]
Sure, I will finish alarm feature first. after that I will do this(this may take long time), I also notice that pinpoint had support it. and I will take a look

**Comment by wu-sheng** [comment]
No activity for months.

**Comment by cicoco** [comment]
not solved in org.springframework.data.redis.listener.RedisMessageListenerContainer#dispatchMessage
