### ISSUE TITLE
java agent启动报错

### ISSUE THREAD

**Issue by taoyuyu** [apache/skywalking#5861]
Question or discussion

___
### Question
java agent启动的时候agent/logs/skywalking-api.log里面有这个错是为什么
`
ERROR 2020-11-19 10:36:32:079 main PluginBootstrap : load plugin [org.apache.skywalking.apm.plugin.thrift.define.client.TServiceClientReceiveInstrumentation] failure.
java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.plugin.thrift.define.client.TServiceClientReceiveInstrumentation
    at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:117)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.skywalking.apm.agent.core.plugin.PluginBootstrap.loadPlugins(PluginBootstrap.java:66)
    at org.apache.skywalking.apm.agent.SkyWalkingAgent.premain(SkyWalkingAgent.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
`

**Comment by wu-sheng** [comment]
Please use English on the github. And, you may use extend class loader or custom class loader

**Comment by taoyuyu** [comment]
以及这种异常
```java
ERROR 2020-11-19 10:36:37:082 main SkyWalkingAgent : Enhance class org.apache.http.impl.client.DefaultRequestDirector error. 
org.apache.skywalking.apm.agent.core.plugin.PluginException: Can't create InstanceMethodsAroundInterceptor.
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.<init>(InstMethodsInter.java:54)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassEnhancePluginDefine.enhanceInstance(ClassEnhancePluginDefine.java:177)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassEnhancePluginDefine.enhance(ClassEnhancePluginDefine.java:74)
        at org.apache.skywalking.apm.agent.core.plugin.AbstractClassEnhancePluginDefine.define(AbstractClassEnhancePluginDefine.java:77)
        at org.apache.skywalking.apm.agent.SkyWalkingAgent$Transformer.transform(SkyWalkingAgent.java:156)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10364)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10302)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10068)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10687)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10634)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10225)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.http.impl.client.AbstractHttpClient.createClientRequestDirector(AbstractHttpClient.java:925)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:782)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.tencent.tdbank.busapi.config.BusConfigManager.requestConfiguration(BusConfigManager.java:703)
        at com.tencent.tdbank.busapi.config.BusConfigManager.requestBusList(BusConfigManager.java:522)
        at com.tencent.tdbank.busapi.config.BusConfigManager.doBusEntryQueryWork(BusConfigManager.java:160)
        at com.tencent.tdbank.busapi.network.ClientMgr.<init>(ClientMgr.java:179)
        at com.tencent.tdbank.busapi.network.Sender.<init>(Sender.java:47)
        at com.tencent.tdbank.busapi.DefaultMessageSender.<init>(DefaultMessageSender.java:100)
        at com.tencent.infra.tdbank.TDBusMessageSender.init(TDBusMessageSender.java:59)
        at com.tencent.infra.tdbank.TDBusMessageSender.access$1500(TDBusMessageSender.java:31)
        at com.tencent.infra.tdbank.TDBusMessageSender$Builder.build(TDBusMessageSender.java:352)
        at com.tencent.infra.monitor.MonitorWriter.<init>(MonitorWriter.java:23)
        at com.tencent.infra.monitor.MonitorClient.<init>(MonitorClient.java:63)
        at com.tencent.infra.monitor.MonitorClient.<init>(MonitorClient.java:17)
        at com.tencent.infra.monitor.MonitorClient$MonitorClientBuilder.build(MonitorClient.java:419)
        at com.tencent.cradle.monitor.CradleMonitor.init(CradleMonitor.java:87)
        at com.tencent.cradle.command.ServerBuilder.build(ServerBuilder.java:49)
        at com.tencent.cradle.command.CradleServer.execute(CradleServer.java:40)
        at com.tencent.cradle.command.CradleServer.main(CradleServer.java:31)
Caused by: java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/InstanceMethodsAroundInterceptor
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:112)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.skywalking.apm.agent.core.plugin.loader.InterceptorInstanceLoader.load(InterceptorInstanceLoader.java:71)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.<init>(InstMethodsInter.java:52)
        ... 45 more
Caused by: java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceMethodsAroundInterceptor
        at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:117)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 55 more
```

**Comment by taoyuyu** [comment]
how i start agent
```shell
java -server -Dio.netty.noPreferDirect=true \
                      -Djava.net.preferIPv4Stack=true \
                      -javaagent:/data/home/ocr/yvestao/cradle/echo_002_10115/agent/skywalking-agent.jar \
                      -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+DisableExplicitGC \
                      -XX:ConcGCThreads=2  -XX:ParallelGCThreads=8 \
                      -XX:G1HeapRegionSize=32M -XX:InitiatingHeapOccupancyPercent=75 \
                      -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps \

```

**Comment by wu-sheng** [comment]
I can't see what your codes like, our tests are here, https://github.com/apache/skywalking/tree/master/test/plugin/scenarios

**Comment by kezhenxu94** [comment]
> ERROR 2020-11-19 10:36:32:079 main PluginBootstrap : load plugin [org.apache.skywalking.apm.plugin.thrift.define.client.TServiceClientReceiveInstrumentation] failure. java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.plugin.thrift.define.client.TServiceClientReceiveInstrumentation 

The first exception is fixed by #5734 , please try the master branch

**Comment by taoyuyu** [comment]
it works, but another exception occured.
```java
ERROR 2020-11-19 20:27:08:133 main SkyWalkingAgent : Enhance class org.apache.http.impl.client.AbstractHttpClient error. 
org.apache.skywalking.apm.agent.core.plugin.PluginException: Can't create InstanceMethodsAroundInterceptor.
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.<init>(InstMethodsInter.java:54)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassEnhancePluginDefine.enhanceInstance(ClassEnhancePluginDefine.java:177)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.ClassEnhancePluginDefine.enhance(ClassEnhancePluginDefine.java:74)
        at org.apache.skywalking.apm.agent.core.plugin.AbstractClassEnhancePluginDefine.define(AbstractClassEnhancePluginDefine.java:77)
        at org.apache.skywalking.apm.agent.SkyWalkingAgent$Transformer.transform(SkyWalkingAgent.java:156)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10364)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10302)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10068)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10687)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10634)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.skywalking.apm.dependencies.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10225)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.tencent.tdbank.busapi.network.ClientMgr.<init>(ClientMgr.java:163)
        at com.tencent.tdbank.busapi.network.Sender.<init>(Sender.java:47)
        at com.tencent.tdbank.busapi.DefaultMessageSender.<init>(DefaultMessageSender.java:100)
        at com.tencent.infra.tdbank.TDBusMessageSender.init(TDBusMessageSender.java:59)
        at com.tencent.infra.tdbank.TDBusMessageSender.access$1500(TDBusMessageSender.java:31)
        at com.tencent.infra.tdbank.TDBusMessageSender$Builder.build(TDBusMessageSender.java:352)
        at com.tencent.infra.monitor.MonitorWriter.<init>(MonitorWriter.java:23)
        at com.tencent.infra.monitor.MonitorClient.<init>(MonitorClient.java:63)
        at com.tencent.infra.monitor.MonitorClient.<init>(MonitorClient.java:17)
        at com.tencent.infra.monitor.MonitorClient$MonitorClientBuilder.build(MonitorClient.java:419)
        at com.tencent.cradle.monitor.CradleMonitor.init(CradleMonitor.java:87)
        at com.tencent.cradle.command.ServerBuilder.build(ServerBuilder.java:49)
        at com.tencent.cradle.command.CradleServer.execute(CradleServer.java:40)
        at com.tencent.cradle.command.CradleServer.main(CradleServer.java:31)
Caused by: java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/InstanceMethodsAroundInterceptor
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:112)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.skywalking.apm.agent.core.plugin.loader.InterceptorInstanceLoader.load(InterceptorInstanceLoader.java:71)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.<init>(InstMethodsInter.java:52)
        ... 49 more
Caused by: java.lang.ClassNotFoundException: Can't find org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceMethodsAroundInterceptor
        at org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader.findClass(AgentClassLoader.java:117)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 59 more

```

@kezhenxu94

**Comment by wu-sheng** [comment]
#5734 would break the booting. The error still makes me feel, you are using ext class loader. Please recheck your classloader.

**Comment by taoyuyu** [comment]
thanks，it works.
