### ISSUE TITLE
logback grpc logging missing trace id

### ISSUE THREAD

**Issue by RealZimboGuy** [apache/skywalking#7151]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ Y] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question

Issue where trace id is showing in stdout and in the log but the trace id is not showing under the log detail in the portal

    <appender name="CONSOLE_HUMAN" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.mdc.TraceIdMDCPatternLogbackLayout">
                <Pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{tid}] [%thread] %-5level %logger{36} -%msg%n</Pattern>
            </layout>
        </encoder>
    </appender>

    <appender name="grpc-log" class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.log.GRPCLogClientAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.mdc.TraceIdMDCPatternLogbackLayout">
                <Pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{tid}] [%thread] %-5level %logger{36} -%msg%n</Pattern>
            </layout>
        </encoder>
    </appender>

        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>8.6.0</version>
        </dependency>

version
apache-skywalking-apm-es7-8.6.0.tar.gz

___
### Bug

the log detail is showing this content 

2021-06-21 16:08:04.195 [TID:61d176602d6140e49accda78790a8fff.54.16242844841900003] [qtp847568453-54] WARN  c.d.v.p.p.services.MsService -invalid transaction id format :Request{merchant='795bf316-cfc3-48fd-8c20-4efed2093722', expirySeconds=0}

tags 
level = WARN
logger = com.de.v.pa.pa.services.MsService
thread = qtp847568453-54

but the TraceID is blank. ie should be able to correlate the related logs but the trace id is not inserting ? 

i assume its most likely something i am doing wrong

- Which company or project?
SELF- testing

**Comment by wu-sheng** [comment]
You could check this, https://github.com/apache/skywalking/blob/master/test/e2e/e2e-service-provider/src/main/resources/logback.xml. We are using this in every commit test.

**Comment by wu-sheng** [comment]
@EvanLjp Anything to add?

**Comment by EvanLjp** [comment]
https://github.com/apache/skywalking/blob/master/test/e2e/e2e-test/src/test/resources/expected/log/logs.yml. It should be working. I suspect it didn't generate any spans in MsService logger because he didn't active the spring annotation plugins.

**Comment by RealZimboGuy** [comment]
@wu-sheng  no difference in the logback file as compared to mine from what i can see

@EvanLjp  can you elaborate on the spring annotation plugin ? 

i added this dependency, but cant see any maven plugins ?  

        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
            <version>8.6.0</version>
        </dependency>

**Comment by RealZimboGuy** [comment]
@EvanLjp  i tried with moving just the apm-spring-async-annotation-plugin-8.6.0 from the optional-plugins directory to the plugins directory but still no change in the traceID showing in logs, my console appender is showing ie,

2021-06-22 07:58:48.655 [TID:25ecd3153fad4251a96f15a90c2c8a0b.56.16243415285020001] [qtp505250106-56] WARN  c.d.v.p.p.services

**Comment by EvanLjp** [comment]
https://github.com/apache/skywalking/blob/master/test/e2e/e2e-service-provider/src/main/resources/logback.xml#:~:text=%3Croot%20level%3D%22INFO,%3C/configuration%3E
Do you config the relationship between root logger and appender?

**Comment by RealZimboGuy** [comment]
RIGHT, I GOT IT :) 

so my issue was i wrapped the grpc logger in an async appender, ie 

    <appender name="GRPC_ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="grpc-log"/>
    </appender>

i removed that and its now working as expected and tagging the traceID.

thanks so much for the assistance, is there an IRC for skywalking or something to ask other random questions ?

**Comment by wu-sheng** [comment]
The slack has been open on the website and github readme.
